
```{r}
#1.set file sources
rm(list=ls())
options(scipen = 999)
setwd("Path/STRATEGIC")
library(dplyr)
```


```{r}
#2.summarize results for 2024-2035
summary = function(model_output, set, sen){
  model_output = model_output[which(model_output$year!="2023"),]
  if((set=="global")&(sen=="uni")){
    arg_setting = list(quo(variable),quo(scenario))
  }else if((set=="region")&(sen=="uni")){
    arg_setting = list(quo(variable),quo(region), quo(scenario))
  }else if((set=="global")&(sen=="multi")){
    arg_setting = list(quo(scenario))
  }else if((set=="region")&(sen=="multi")){
    arg_setting = list(quo(region), quo(scenario))
  }
  sums <- model_output %>%
    dplyr::group_by(!!! arg_setting) %>% # Does not include model_output!
    dplyr::summarise(
      total_deaths_lci = sum(total_deaths_lci),
      total_deaths_uci = sum(total_deaths_uci),
      total_deaths = sum(total_deaths),
      
      total_vials_lci = sum(total_vials_lci),
      total_vials_uci = sum(total_vials_uci),
      total_vials = sum(total_vials),
      
      total_cost_lci = sum(total_cost_lci),
      total_cost_uci = sum(total_cost_uci),
      total_cost = sum(total_cost),
      
      total_deaths_averted_lci = sum(total_deaths_averted_lci),
      total_deaths_averted_uci = sum(total_deaths_averted_uci),
      total_deaths_averted = sum(total_deaths_averted),
      
      total_YLL_lci = sum(total_YLL_lci),
      total_YLL_uci = sum(total_YLL_uci),
      total_YLL = sum(total_YLL),
      
      total_YLL_averted_lci = sum(total_YLL_averted_lci),
      total_YLL_averted_uci = sum(total_YLL_averted_uci),
      total_YLL_averted = sum(total_YLL_averted),
      
      vaccinated_lci = sum(vaccinated_lci),
      vaccinated_uci = sum(vaccinated_uci),
      vaccinated = sum(vaccinated),
      
      fully_vaccinated_lci = sum(fully_vaccinated_lci),
      fully_vaccinated_uci = sum(fully_vaccinated_uci),
      fully_vaccinated = sum(fully_vaccinated),
      
      RIG_lci = sum(RIG_lci),
      RIG_uci = sum(RIG_uci),
      RIG = sum(RIG),
      
    )
    
  sums$cost_per_death_averted_lci <-  sums$total_cost_lci/sums$total_deaths_averted_uci
  sums$cost_per_death_averted_uci <-  sums$total_cost_uci/sums$total_deaths_averted_lci
  sums$cost_per_death_averted <-  sums$total_cost/sums$total_deaths_averted
  
  sums$cost_per_YLL_averted_lci <-  sums$total_cost_lci/sums$total_YLL_averted_uci
  sums$cost_per_YLL_averted_uci <-  sums$total_cost_uci/sums$total_YLL_averted_lci
  sums$cost_per_YLL_averted <-  sums$total_cost/sums$total_YLL_averted
  
  sums$deaths_averted_per_100k_vaccinated_lci <-  sums$total_deaths_averted_lci/sums$vaccinated_uci/100000
  sums$deaths_averted_per_100k_vaccinated_uci <-  sums$total_deaths_averted_uci/sums$vaccinated_lci/100000
  sums$deaths_averted_per_100k_vaccinated <-  sums$total_deaths_averted/sums$vaccinated/100000
  
  return(sums)
}

out <- read.csv("output/un_region_stats.csv", stringsAsFactors=FALSE)
out_horizon = summary(out,set="region",sen="uni")
write.csv(out_horizon,"output/un_region_stats_horizon(24-35).csv",row.names=F)

out <- read.csv("output/un_global_stats.csv", stringsAsFactors=FALSE)
out_horizon = summary(out,set="global",sen="uni")
write.csv(out_horizon,"output/un_global_stats_horizon(24-35).csv",row.names=F)

out <- read.csv("output/region_stats.csv", stringsAsFactors=FALSE)
out_horizon = summary(out,set="region",sen="multi")
write.csv(out_horizon,"output/region_stats_horizon(24-35).csv",row.names=F)

out <- read.csv("output/global_stats.csv", stringsAsFactors=FALSE)
out_horizon = summary(out,set="global",sen="multi")
write.csv(out_horizon,"output/global_stats_horizon(24-35).csv",row.names=F)
```
