---
title: "STRATEGIC"
output: html_document
---

#################################################################
#                                                               #
#  Strategies to inTerrupt RAbies Transmission for the          #
#  Elimination Goal by 2030 In China (STRATEGIC) study          #
#                                                               #        
#  sensitivity analysis                                         #
#  This file is used for the sensitivity analyses               #
#  of dog population                                            #
#  URL: https://github.com/katiehampson1978/rabies_PEP_access   #
#  Ref.: The Lancet Infectious Diseases 2019; 19(1): 102-11.    #
#                                                               #
#################################################################


```{r}
#1-1.set file sources
rm(list=ls())
setwd("Path/STRATEGIC/additional analyses/dog vial price/")
source("R/1.rabies probability calculation.R")
source("R/2.medical care probability calculation.R")
source("R/3.DALYs calculation.R")
source("R/4.time of strategy.R")
source("R/6.multivariate analysis.R")
source("R/7.results summary.R")
source("R/8.plot_function.R")
```


```{r}
library(triangle)
library(dplyr)
```


```{r}
#1-2.parameters from files
DALYrabies_input <- read.csv("data/DALY.csv")
LE2022 <- read.csv("data/lifetable.csv")$value
data <- read.csv("data/data.csv")
dogs <- read.csv(file="data/dogs_pop_traj.csv", stringsAsFactors = FALSE)
elimination_traj <- read.csv(file="data/rabies_traj.csv")
rabies <- read.csv("data/baseline_incidence.csv")
params <- read.csv("data/bio_data.csv")
vacc <- read.csv("data/vaccine_use.csv")

#1-3.parameters by settings
hrz=length(2023:2035)
discount=0.03
n=1000
dog_vial_price_pre <- c(10,11)
cost_constriant <- as.data.frame(matrix(0,nrow=5,ncol=4))
colnames(cost_constriant) <- c("price","death","cost","ICER")
cost_constriant$price[1:2] <-  dog_vial_price_pre
cost_constriant$ICER[3:5] <- c(0,10410,31230)
```


```{r}
#2.cost constriant analysis
for(n_time in 1:2){
  dog_vial_price = dog_vial_price_pre[n_time]
  #2.probabilistic sensitivity analyses (PSA)
# 1)SQ - status quo
set.seed(1)
scenario_a1 <- multivariate_analysis(ndraw=n, horizon=hrz, GAVI_status="none", DogVax_TF=F, VaxRegimen="Updated TRC",
                                     DALYrabies=DALYrabies_input, LE=LE2022, RIG_status="high risk", discount=discount, breaks="5yr", IBCM=FALSE)

# 2)improved PEP
set.seed(1)
scenario_a2 <- multivariate_analysis(ndraw=n, horizon=hrz, GAVI_status="base", DogVax_TF=F, VaxRegimen="Updated TRC",
                                     DALYrabies=DALYrabies_input, LE=LE2022, RIG_status="high risk", discount=discount, breaks="5yr", IBCM=FALSE)

# 3a)improved Dog Vax
set.seed(1)
scenario_a3 <- multivariate_analysis(ndraw=n, horizon=hrz, GAVI_status="none", DogVax_TF=T, VaxRegimen="Updated TRC",
                                       DALYrabies=DALYrabies_input, LE=LE2022, RIG_status="high risk", discount=discount, breaks="5yr", IBCM=FALSE)

# 3b)improved PEP plus  Dog Vax
set.seed(1)
scenario_a4 <- multivariate_analysis(ndraw=n, horizon=hrz, GAVI_status="base", DogVax_TF=T, VaxRegimen="Updated TRC",
                                       DALYrabies=DALYrabies_input, LE=LE2022, RIG_status="high risk", discount=discount, breaks="5yr", IBCM=FALSE)

# 4a)IBCM
set.seed(1)
scenario_a5 <- multivariate_analysis(ndraw=n, horizon=hrz, GAVI_status="none", DogVax_TF=F, VaxRegimen="Updated TRC",
                                       DALYrabies=DALYrabies_input, LE=LE2022, RIG_status="high risk", discount=discount, breaks="5yr", IBCM=TRUE)

# 4b)Improved PEP plus IBCM
set.seed(1)
scenario_a6 <- multivariate_analysis(ndraw=n, horizon=hrz, GAVI_status="base", DogVax_TF=F, VaxRegimen="Updated TRC",
                                     DALYrabies=DALYrabies_input, LE=LE2022, RIG_status="high risk", discount=discount, breaks="5yr", IBCM=TRUE)

# 4c)Improved Dog vax plus IBCM
set.seed(1)
scenario_a7 <- multivariate_analysis(ndraw=n, horizon=hrz, GAVI_status="none", DogVax_TF=T, VaxRegimen="Updated TRC",
                                       DALYrabies=DALYrabies_input, LE=LE2022, RIG_status="high risk", discount=discount, breaks="5yr", IBCM=TRUE)

# 4d)Improved PEP plus Dog Vax plus IBCM
set.seed(1)
scenario_a8 <- multivariate_analysis(ndraw=n, horizon=hrz, GAVI_status="base", DogVax_TF=T, VaxRegimen="Updated TRC",
                                       DALYrabies=DALYrabies_input, LE=LE2022, RIG_status="high risk", discount=discount, breaks="5yr", IBCM=TRUE)

#result summary#
out <- rbind.data.frame(
  cbind.data.frame(scenario_a1, scenario="a1"),
  cbind.data.frame(scenario_a2, scenario="a2"),
  cbind.data.frame(scenario_a3, scenario="a3"),
  cbind.data.frame(scenario_a4, scenario="a4"),
  cbind.data.frame(scenario_a5, scenario="a5"),
  cbind.data.frame(scenario_a6, scenario="a6"),
  cbind.data.frame(scenario_a7, scenario="a7"),
  cbind.data.frame(scenario_a8, scenario="a8"))
regions <- unique(out$region)
scenarios <- unique(out$scenario)
yrs <- unique(out$year)
gavi_info <- read.csv("data/data.csv", stringsAsFactors=FALSE)
out <- merge(out, data.frame(region=gavi_info$region), by="region", all.x=TRUE)

out$cost_per_death_averted <-  out$total_cost/out$total_deaths_averted
out$cost_per_YLL_averted <-  out$total_cost/out$total_YLL_averted
out$deaths_averted_per_100k_vaccinated <-  out$total_deaths_averted/out$vaccinated/100000

# Create summary outputs per year
out_horizon = region_horizon_iter(out)
region_summary_yr = multivar_region_summary(out, year = TRUE)
global_summary_yr = multivar_summary(region_summary_yr[which(region_summary_yr$region=="China"),], year=TRUE, setting="global")
folder_name=""

###########################
# 2-1.ICER tables prepare #
###########################
undisc_global <- global_summary_yr
global_hor <- scenario_prep(undisc_global)[,c(1,2,5,11)]
global_hor[,c(3:4)] <- round(global_hor[,c(3:4)],4)
ICER_pre <- as.data.frame(matrix(0,8,4))
rownames(ICER_pre) <- c("scenario 1","scenario 2","scenario 3a","scenario 3b","scenario 4a","scenario 4b","scenario 4c","scenario 4d")
colnames(ICER_pre) <- c("death_2030","cost_2030","death_2035","cost_2035")
for(i in 1:8){
  ICER_pre[i,1] <- sum(global_hor$total_deaths[which(global_hor$scenario==i)][1:8])
  ICER_pre[i,2] <- sum(global_hor$total_cost[which(global_hor$scenario==i)][1:8])
  ICER_pre[i,3] <- sum(global_hor$total_deaths[which(global_hor$scenario==i)])
  ICER_pre[i,4] <- sum(global_hor$total_cost[which(global_hor$scenario==i)])
}
# write.csv(ICER_pre,row.names = T, paste("figures and tables/death_cost_scenario.csv"))

ICER_pre_US <- ICER_pre
ICER_pre_US$cost_2030 <- ICER_pre_US$cost_2030/6.8996
ICER_pre_US$cost_2035 <- ICER_pre_US$cost_2035/6.8996
# write.csv(ICER_pre_US,row.names = T, paste("figures and tables/death_cost_scenario_US.csv"))

###################
# 2-2.ICER tables #
###################

ICER_main <- as.data.frame(matrix(0,7,6))
rownames(ICER_main) <- c("scenario 2 v.s. 1","scenario 3a v.s. 1","scenario3b v.s. 1","scenario4a v.s. 1","scenario 4b v.s. 1","scenario 4c v.s. 1","scenario 4d v.s. 1")
colnames(ICER_main) <- c("death_2030","cost_2030","ICER_2030","death_2035","cost_2035","ICER_2035")
for(i in 2:8){
  ICER_main[i-1,1] <- -(ICER_pre[i,1]-ICER_pre[1,1])
  ICER_main[i-1,2] <- (ICER_pre[i,2]-ICER_pre[1,2])
  ICER_main[i-1,3] <- ICER_main[i-1,2]/ICER_main[i-1,1]
  ICER_main[i-1,4] <- -(ICER_pre[i,3]-ICER_pre[1,3])
  ICER_main[i-1,5] <- (ICER_pre[i,4]-ICER_pre[1,4])
  ICER_main[i-1,6] <- ICER_main[i-1,5]/ICER_main[i-1,4]
}
ICER_main <- format(signif(ICER_main, 12), nsmall=4, big.mark=",", trim=TRUE)
# write.csv(ICER_main,row.names = T, paste("figures and tables/ICER_scenario.csv"))

ICER_main_US <- as.data.frame(matrix(0,7,6))
rownames(ICER_main_US) <- c("scenario 2 v.s. 1","scenario 3a v.s. 1","scenario3b v.s. 1","scenario4a v.s. 1","scenario 4b v.s. 1","scenario 4c v.s. 1","scenario 4d v.s. 1")
colnames(ICER_main_US) <- c("death_2030","cost_2030","ICER_2030","death_2035","cost_2035","ICER_2035")
for(i in 2:8){
  ICER_main_US[i-1,1] <- -(ICER_pre_US[i,1]-ICER_pre_US[1,1])
  ICER_main_US[i-1,2] <- (ICER_pre_US[i,2]-ICER_pre_US[1,2])
  ICER_main_US[i-1,3] <- ICER_main_US[i-1,2]/ICER_main_US[i-1,1]
  ICER_main_US[i-1,4] <- -(ICER_pre_US[i,3]-ICER_pre_US[1,3])
  ICER_main_US[i-1,5] <- (ICER_pre_US[i,4]-ICER_pre_US[1,4])
  ICER_main_US[i-1,6] <- ICER_main_US[i-1,5]/ICER_main_US[i-1,4]
}
# ICER_main_US <- format(signif(ICER_main_US, 12), nsmall=4, big.mark=",", trim=TRUE)
ICER_main_US <- round(ICER_main_US,4)
cost_constriant$death[n_time] <- ICER_main_US[6,4]
cost_constriant$cost[n_time] <- ICER_main_US[6,5]
cost_constriant$ICER[n_time] <- ICER_main_US[6,6]
}
cost_constriant$death[3:5] <- cost_constriant$death[1]
cost_constriant <- lapply(cost_constriant, as.numeric)
# cost_constriant <- as.data.frame(as.numeric(as.matrix(cost_constriant)))
cost_constriant$cost[3:5] <- cost_constriant$ICER[3:5]*cost_constriant$death[1]
for(i in 3:5){
  cost_constriant$price[i] <- (cost_constriant$cost[i]-cost_constriant$cost[1])/(cost_constriant$cost[2]-cost_constriant$cost[1])+cost_constriant$price[1]
}
cut_off <- matrix(0,2,3)
colnames(cut_off) <- c("0","1 times GDP per capita","3 times GDP per capita")
rownames(cut_off) <- c("ICER","dog vials price")
cut_off[1,] <- c(0,10410,31230)
cut_off[2,] <- cost_constriant$price[3:5]

################################################
# 2-3.results for the cost constriant analysis #
################################################
print(cut_off)
```

